// New folder (5)/client/src/app/shared/components/modal/modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
    selector: 'app-modal',
    standalone: true,
    imports: [CommonModule],
    templateUrl: './modal.component.html',
})

export class ModalComponent {
    @Input() isOpen = false;
    @Input() title = '';
    @Input() width = 'max-w-xl';
    @Output() onClose = new EventEmitter<void>();

    closeModal() {
        this.onClose.emit();
    }
}

<div
  *ngIf="isOpen"
  class="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto py-10 px-4"
>
  <div
    class="fixed inset-0 bg-black/20 backdrop-blur-sm transition-opacity duration-300"
    (click)="closeModal()"
  ></div>

  <div
    class="w-full {{
      width
    }} bg-white rounded-2xl shadow-xl p-6 relative transition-all duration-300"
    (click)="$event.stopPropagation()"
  >
    <button
      type="button"
      (click)="closeModal()"
      class="absolute top-3 right-3 text-black hover:text-red-400 text-4xl"
      aria-label="Close modal"
    >
      &times;
    </button>

    <h2 class="text-xl font-semibold mb-4 text-black">{{ title }}</h2>

    <div class="overflow-y-auto scrollbar max-h-[70vh]">
      <ng-content></ng-content>
    </div>
  </div>
</div>

// marketing2/src/components/(sheared)/Modal.tsx
import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface ModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  children: React.ReactNode;
  width?: string; // e.g., 'max-w-xl', 'max-w-2xl'
}

const Modal: React.FC<ModalProps> = ({
  isOpen,
  onClose,
  title,
  children,
  width = 'max-w-xl',
}) => {
  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          key="backdrop"
          className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/20 backdrop-blur-sm overflow-y-auto py-10 px-4"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose} // Close when backdrop is clicked
        >
          <motion.div
            key="modal"
            initial={{ y: -50, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            exit={{ y: -50, opacity: 0 }}
            transition={{ type: 'spring', damping: 20, stiffness: 300 }}
            className={`w-full ${width}   text-white bg-white rounded-2xl shadow-xl p-6 relative`}
            onClick={(e) => e.stopPropagation()} // Prevent backdrop close when clicking modal content
          >
            <button
              type='button'
              onClick={onClose}
              className="absolute top-3 right-3 text-black hover:text-red-400 text-4xl"
              aria-label="Close modal"
            >
              &times;
            </button>

            <h2 className="text-xl font-semibold mb-4 text-black">{title}</h2>

            <div className="overflow-y-auto scrollbar max-h-[70vh]">
              {children}
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default Modal;
